### ISSUE TITLE
Unable to set correct viewport size.

### ISSUE THREAD

**Issue by Motivationking** [CheshireCaat/puppeteer-with-fingerprints#10] opened 2023-04-22 06:06 UTC
`while (true) {

        let fingerPrint = [
            ['Android', 'Chrome']
        ];
            
        const fp= await plugin.fetch(KEY, {
            tags: fingerPrint,
            // tags: ['Microsoft Windows', 'Chrome'],
        });

        // console.log(fp)
        await plugin.useFingerprint(fp)
        let browser;

        try {
            browser = await plugin.launch({
                headless: false,
                // timeout: 0, // disables the default timeout
                // slowMo: 100, // disables the slow motion
                // ignoreHTTPSErrors: true,
                // devtools: false,
                // protocolTimeout: 600000, // set the protocolTimeout to 5 minutes
            });
            return browser;

        } catch (error) {
            console.log(`Error With Fingerprints: ${error.message}`)
             // await browser.close() // not working, also give me error is: browser is undefined
            if (browser && browser.process() && !browser.process().killed) {
                browser.process().kill();
            }
            continue
        } 
    }`
**OUTPUT-- Error With Fingerprints: **Unable to set correct viewport size.****

the major isssue is BROWSER KEEPS OPENED EVEN I HANDLED ERROR, i dont want to quit while loop after handle eror thats why im not used  process.exit(1) , i just want which browser instance givesme error,  just closed it and create new browser..

**Comment by Motivationking** [comment] 2023-04-22 07:48
sir im not master in js, i just know basics about js and node js, please provide any solution

**Comment by Motivationking** [comment] 2023-04-22 08:18
so you saved browser fingerprints in computer?

**Comment by Motivationking** [comment] 2023-04-22 08:18
can you please guide my step by step?

**Comment by Motivationking** [comment] 2023-04-22 08:27
no, no... don't write code, but i didn't get what you saying in these steps:

- always started the browser with a custom profile folder.

- iterated over all the OS processes to find all the browser processes

- sent the proper signal to the browser process that I needed to close, which could be detected via cmd because of the custom profile folder.

**Comment by Motivationking** [comment] 2023-04-22 08:37
can you do it for me, i'll ready to pay you

**Comment by Motivationking** [comment] 2023-04-22 09:55
sir, one more question, can we use puppeteer-stealth, puppeteer-extra with puppeteer-with-fingerprints??

**Comment by zulkar-9** [comment] 2023-04-22 16:47
> `while (true) {
> 
> ```
>     let fingerPrint = [
>         ['Android', 'Chrome']
>     ];
>         
>     const fp= await plugin.fetch(KEY, {
>         tags: fingerPrint,
>         // tags: ['Microsoft Windows', 'Chrome'],
>     });
> 
>     // console.log(fp)
>     await plugin.useFingerprint(fp)
>     let browser;
> 
>     try {
>         browser = await plugin.launch({
>             headless: false,
>             // timeout: 0, // disables the default timeout
>             // slowMo: 100, // disables the slow motion
>             // ignoreHTTPSErrors: true,
>             // devtools: false,
>             // protocolTimeout: 600000, // set the protocolTimeout to 5 minutes
>         });
>         return browser;
> 
>     } catch (error) {
>         console.log(`Error With Fingerprints: ${error.message}`)
>          // await browser.close() // not working, also give me error is: browser is undefined
>         if (browser && browser.process() && !browser.process().killed) {
>             browser.process().kill();
>         }
>         continue
>     } 
> }`
> ```
> 
> **OUTPUT-- Error With Fingerprints: Unable to set correct viewport size.**
> 
> the major isssue is BROWSER KEEPS OPENED EVEN I HANDLED ERROR, i dont want to quit while loop after handle eror thats why im not used process.exit(1) , i just want which browser instance givesme error, just closed it and create new browser..

1. Change screen resolution of your display to 100% 
2.  Use parameters "max-height" "max-width" of fetch to filter out fingerprints with large screen resolution

**Comment by Motivationking** [comment] 2023-04-22 17:12
`Use parameters "max-height" "max-width" of fetch to filter out fingerprints with large screen resolution`
how to do that?

**Comment by zulkar-9** [comment] 2023-04-23 09:06
In the Windows taskbar, go to the screen settings and check the "Scale and layout" field. I had the same problem, and this method solved.

**Comment by bannyhm** [comment] 2023-05-04 11:16
Hello.
After the above recommendations with a change in Windows - "Scale and layout", the problem with viewprot was not solved. Conducted several tests:

1. tags: ['Android','Chrome'],
 minBrowserVersion: 112,
 MinWidth: 400,
minHeight: 600,
maxWidth: 900,
maxHeight: 1020

As a result, there is a problem with the resulting fingerprints, with the specified MinWidth: 400 I get a fingerprints with Width: 360px.

2. tags: ['Microsoft Windows', 'Chrome'],
 minBrowserVersion: 110,
 minWidth: 1920,
 minHeight: 1080,
 maxWidth: 1920,
 maxHeight: 1080

As a result, there are no problems with viewprot, and I get only fingerprints with Width: 1920px.

Tell me, what other possible solutions to the problem with Viewport for fingerprints Android?

**Comment by DangerLifter** [comment] 2023-06-27 07:07
Confirm this issue. Hope fix will be implemented in recent update

**Comment by bablosoft** [comment] 2023-07-07 10:17
This issue should be fixed in latest update.

**Closed by bablosoft** 2023-07-07 10:17 UTC

**Comment by DangerLifter** [comment] 2023-07-10 10:33
@bablosoft Technically it is resolved due "Viewport size' error never happens. But proposed above solution still makes sense. It seems correct behavior catch exception and close browser if attempt to configure throws any error right after browser is constructed but not returned to external caller. otherwise external caller are not able to close it properly.

**Comment by CheshireCaat** [comment] 2023-07-10 10:42
@DangerLifter we'll improve handling of this error separately in future updates.

**Comment by mannok** [comment] 2023-08-05 10:48
I am one of the victims of this problem. May I know what is causing this issue?  I can sure this definitely related to fingerprint as the same fingerprint always comes to the same problem.

If this is a known issue, please let me know so that I can avoid it

**Comment by bablosoft** [comment] 2023-08-05 10:57
@mannok right now it is fixed, are you using old version?

**Comment by mannok** [comment] 2023-08-05 10:58
@bablosoft , can confirm I have updated to the latest version already.

```
  "dependencies": {
    "delay": "^6.0.0",
    "fingerprint-injector": "^2.1.37",
    "p-retry": "^5.1.2",
    "playwright": "^1.36.2",
    "puppeteer": "^20.9.0",
    "puppeteer-with-fingerprints": "^1.3.3",
    "systeminformation": "^5.18.11",
    "tslib": "~2.5"
  }
```

**Comment by bablosoft** [comment] 2023-08-05 11:06
Sharing fingerprints is prohibited.

Latest version gives warning, not error, you can ignore it.

**Comment by mannok** [comment] 2023-08-05 11:59
@bablosoft But the problem now is those problematic fingerprints cause my browser's score so low, also, the browser window is unusally small... (seems it is caused by my screen scale)

FYR: the larger one is the normal one
![image](https://github.com/CheshireCaat/puppeteer-with-fingerprints/assets/458220/2469017e-83de-434c-8699-2b098ce99ea8)

**Comment by bablosoft** [comment] 2023-08-05 12:02
Please use PerfectCanvas. If you still experience any problems, please attach detailed description and create the new issue.

**Comment by bablosoft** [comment] 2023-08-05 18:43
@Firegarden If this is the case, that would be a major issue. But I don't see anything wrong with this test. Here is example with changed fingerprint.

![](https://i.imgur.com/q3c8rMg.png)

**Comment by bablosoft** [comment] 2023-08-06 11:28
@Firegarden I don't see any issues. 

![](https://i.imgur.com/04SVZTm.png)

Please don't write here, this is unrelated to original issue.

If you have any problem, please create new issue, attach source and describe in more details.
