### ISSUE TITLE
reopen parallel launch browsers

### ISSUE THREAD

**Issue by dmitry200** [CheshireCaat/puppeteer-with-fingerprints#26] opened 2023-07-02 20:18 UTC
This error means that you are trying to run several applications from same folder.

If you are not trying to do so, please reopen the ticket and attach all necessary information to reproduce the problem: source code and detailed description.

Avoid to place your key here.

Note that C# is not supported, so source must be written with node.js.

_Originally posted by @bablosoft in https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/25#issuecomment-1616802080_

**Comment by dmitry200** [comment] 2023-07-02 20:19
try
      {

        const fingerprint = await plugin.fetch('MYKEY', {
            tags: ['Microsoft Windows', 'Chrome'],
            minBrowserVersion: 112,
            minWidth: 1312,
            minHeight: 768,
            maxWidth: 1920,
            maxHeight: 1080,
            usePerfectCanvas: true
        });

        plugin.useFingerprint(fingerprint);

          plugin.useProxy(`${process.argv[3]}:${process.argv[4]}:${process.argv[5]}:${process.argv[6]}`, {
            changeTimezone: true,
            changeGeolocation: true,
            changeBrowserLanguage: false,
          });


            var browser = await plugin.launch({ 

                headless: false,
                userDataDir: `C:\\Users\\username\\Desktop\\dir\\${process.argv[2]}`,
                executablePath: `C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe`,
                args: [
                        `--no-sandbox`,
                        `--disable-dev-shm-usage`, //https://github.com/puppeteer/puppeteer/issues/1321#issuecomment-378361236
                        `--disable-gpu`,
                ],
            });
              console.log(browser.wsEndpoint());

      } catch(e) {
          console.log(e);
      }

      await sleep(999999);

I run this script from my c# and there I already connect to the browser, I dont understand what you mean by "This error means that you are trying to run several applications from the same folder."

what is the best way to solve this?

**Comment by dmitry200** [comment] 2023-07-02 20:19
@bablosoft make 10 folders and run a copy from them in each thread? its stupid

why did I buy a license then?

**Comment by bablosoft** [comment] 2023-07-02 20:46
Duplicate of #25 closing

**Closed by bablosoft** 2023-07-02 20:46 UTC
